update to latest versions and remove deprecation warnings

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -1,13 +1,10 @@
-name: Integration tests
+name: Integration Tests
 
 on:
-  workflow_dispatch: null
   push:
     branches:
       - main
       - dev
-
-# Define reusable steps
 
 jobs:
   integration_tests:
@@ -16,17 +13,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        user:
-          - USER_1
-          - USER_2
-          - USER_3
-          - USER_4
-    env:
-      EXIT_STATUS: 0
+        user: ["USER_1", "USER_2", "USER_3", "USER_4"]
 
-    # Job for each user
     steps:
-      - name: Clone Repository
+      - name: Checkout Repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
@@ -35,109 +25,103 @@ jobs:
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
-          go-version: 'stable'
-      - run: go version
-      - run: make deps
+          go-version: '1.x'
 
-      - name: Update system packages
-        run: sudo apt-get update -y
-
-      - name: Install system deps
-        run: sudo apt-get install -y build-essential
-
-      - name: Setup Python
+      - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.x'
 
-      - name: Install Python deps
-        run: pip3 install requests wheel boto3
+      - name: Install Dependencies
+        run: |
+          make deps
+          sudo apt-get update -y
+          sudo apt-get install -y build-essential
+          pip install requests wheel boto3
 
       - name: Install go-junit-report
         run: go install github.com/jstemmer/go-junit-report/v2@latest
 
+      - name: Set Environment Variables
+        run: |
+          case "${{ matrix.user }}" in
+            "USER_1")
+              echo "TEST_TAGS=acceptance,backup,domain,domainrecord,domains,domainzonefile,firewall,firewalldevice,firewalls,helper,image,images,instance,instanceconfig,instancedisk,instanceip" >> $GITHUB_ENV
+              echo "LINODE_TOKEN=${{ secrets.LINODE_TOKEN_USER_1 }}" >> $GITHUB_ENV
+              ;;
+            "USER_2")
+              echo "TEST_TAGS=instancenetworking,instancesharedips,instancetype,instancetypes,ipv6range,ipv6ranges,kernel,kernels,lke,lkeclusters" >> $GITHUB_ENV
+              echo "LINODE_TOKEN=${{ secrets.LINODE_TOKEN_USER_2 }}" >> $GITHUB_ENV
+              ;;
+            "USER_3")
+              echo "TEST_TAGS=nb,nbconfig,nbconfigs,nbnode,nbs,networkingip,obj,objbucket,objcluster,objkey,profile,rdns" >> $GITHUB_ENV
+              echo "LINODE_TOKEN=${{ secrets.LINODE_TOKEN_USER_3 }}" >> $GITHUB_ENV
+              ;;
+            "USER_4")
+              echo "TEST_TAGS=lkenodepool,lkeversions,region,regions,sshkey,sshkeys,stackscript,stackscripts,token,user,users,vlan,volume,volumes,vpc,vpcs" >> $GITHUB_ENV
+              echo "LINODE_TOKEN=${{ secrets.LINODE_TOKEN_USER_4 }}" >> $GITHUB_ENV
+              ;;
+          esac
+
       - name: Set report filename
-        run: echo "REPORT_FILENAME_${{ matrix.user }}=$(date +'%Y%m%d%H%M')_terraform_test_report_${{ matrix.user }}.xml" >> $GITHUB_ENV
+        id: set-report-filename
+        run: echo "REPORT_FILENAME=$(date +'%Y%m%d%H%M')_terraform_test_report_${{ matrix.user }}.xml" >> $GITHUB_ENV
 
-      - name: Determine test tags
+      - name: Run Integration Tests
         run: |
-          if [[ "${{ matrix.user }}" == "USER_1" ]]; then
-            echo "acceptance,backup,domain,domainrecord,domains,domainzonefile,firewall,firewalldevice,firewalls,helper,image,images,instance,instanceconfig,instancedisk,instanceip"
-          elif [[ "${{ matrix.user }}" == "USER_2" ]]; then
-            echo "instancenetworking,instancesharedips,instancetype,instancetypes,ipv6range,ipv6ranges,kernel,kernels,lke,lkeclusters,lkenodepool,lkeversions"
-          elif [[ "${{ matrix.user }}" == "USER_3" ]]; then
-            echo "nb,nbconfig,nbconfigs,nbnode,nbs,networkingip,obj,objbucket,objcluster,objkey,profile,rdns"
-          elif [[ "${{ matrix.user }}" == "USER_4" ]]; then
-            echo "region,regions,sshkey,sshkeys,stackscript,stackscripts,token,user,users,vlan,volume,volumes,vpc,vpcs"
-          else
-            echo ""
-          fi
-        shell: bash
-        env:
-          TEST_TAGS: ${{ steps.determine-test-tags.outputs.stdout }}
-          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN_USER_${{ matrix.user }} }}
-
-      - name: Run Integration Tests for User ${{ matrix.user }}
-        run: |
-          if ! make TEST_TAGS="${{ env.TEST_TAGS }}" int-test | go-junit-report -set-exit-code > "$REPORT_FILENAME_${{ matrix.user }}"; then
+          if ! make TEST_TAGS="${{ env.TEST_TAGS }}" int-test | go-junit-report -set-exit-code > $REPORT_FILENAME; then
             echo "EXIT_STATUS=1" >> $GITHUB_ENV
           fi
-          cat "$REPORT_FILENAME_${{ matrix.user }}"
+          cat $REPORT_FILENAME
+        env:
+          LINODE_TOKEN: ${{ env.LINODE_TOKEN }}
 
-      - name: Upload test report as artifact
+      - name: Upload Test Report
         uses: actions/upload-artifact@v4
         with:
-          name: test-report-file
-          path: "${{ env.REPORT_FILENAME_${{ matrix.user }} }}"
+          name: test-report
+          path: '*.xml'
 
-# Final processing steps
-process-upload-report:
-  runs-on: ubuntu-latest
-  needs: [integration_tests]
+      - name: Test Execution Status Handler
+        run: |
+          if [[ "$EXIT_STATUS" != 0 ]]; then
+            echo "Test execution contains failure(s), check Run Integration Tests step above"
+            exit $EXIT_STATUS 
+          else
+            echo "Tests Passed!"
+          fi
 
-  steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-        submodules: 'recursive'
 
-    - name: Download test report
-      uses: actions/download-artifact@v4
-      with:
-        name: test-report-file
+  process-upload-report:
+    runs-on: ubuntu-latest
+    needs: [integration_tests]
+    if: always() # Run even if previous job fails
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.x'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          submodules: 'recursive'
 
-    - name: Merge all test xmls in output directory
-      run: |
-        python tod_scripts/merge_terraform_results.py
+      - name: Download test report
+        uses: actions/download-artifact@v4
+        with:
+          name: test-report
 
-    - name: Add additional information to XML report
-      run: |
-        filename=$(ls | grep -E '^[0-9]{12}_terraform_merged_report\.xml$')
-        python tod_scripts/add_to_xml_test_report.py \
-        --branch_name "${GITHUB_REF#refs/*/}" \
-        --gha_run_id "$GITHUB_RUN_ID" \
-        --gha_run_number "$GITHUB_RUN_NUMBER" \
-        --xmlfile "${filename}"
+      - name: Merge Test Reports
+        run: python tod_scripts/merge_terraform_results.py
 
-    - name: Upload test results to bucket
-      run: |
-        report_filename=$(ls | grep -E '^[0-9]{12}_terraform_merged_report\.xml$')
-        python3 tod_scripts/test_report_upload_script.py "${report_filename}"
-      env:
-        LINODE_CLI_OBJ_ACCESS_KEY: ${{ secrets.LINODE_CLI_OBJ_ACCESS_KEY }}
-        LINODE_CLI_OBJ_SECRET_KEY: ${{ secrets.LINODE_CLI_OBJ_SECRET_KEY }}
+      - name: Add Information to XML Report
+        run: |
+          ls -l *.xml
+          filename=$(ls | grep -E '^[0-9]{12}_terraform_merged_report.xml$') 
+          python tod_scripts/add_to_xml_test_report.py --branch_name "${GITHUB_REF#refs/*/}" --gha_run_id "${GITHUB_RUN_ID}" --gha_run_number "${GITHUB_RUN_NUMBER}" --xmlfile "${filename}"
 
-    - name: Test Execution Status Handler
-      run: |
-        if [[ "$EXIT_STATUS" != 0 ]]; then
-          echo "Test execution contains failure(s)"
-          exit $EXIT_STATUS
-        else
-          echo "Tests passed!"
-        fi
+      - name: Upload Test Results
+        run: |
+          filename=$(ls | grep -E '^[0-9]{12}_terraform_merged_report.xml$') 
+          python3 tod_scripts/test_report_upload_script.py "${filename}"
+        env:
+          LINODE_CLI_OBJ_ACCESS_KEY: ${{ secrets.LINODE_CLI_OBJ_ACCESS_KEY }}
+          LINODE_CLI_OBJ_SECRET_KEY: ${{ secrets.LINODE_CLI_OBJ_SECRET_KEY }}
