fix: edit test.yml to allow gha to mark build as x when tests fail (#1112)
* edit integration_tests.yml to return proper exit status when tests fail

* typo

* debug gha

* found the issue. missed replacing json with xml :(

* update names and removing TEST_PKG

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -9,6 +9,8 @@ jobs:
   integration_tests:
     name: Run integration tests
     runs-on: ubuntu-latest
+    env:
+      EXIT_STATUS: 0
     steps:
       - name: Clone Repository
         uses: actions/checkout@v4
@@ -37,25 +39,29 @@ jobs:
       - name: Install go-junit-report
         run: go install github.com/jstemmer/go-junit-report/v2@latest
 
-      - run: |
+      - name: Run Integration Tests
+        run: |
           timestamp=$(date +'%Y%m%d%H%M')
-          report_filename="${timestamp}_terraform_test_report.json"
-          make testacc TESTARGS="-json" | tee "$report_filename"
+          report_filename="${timestamp}_terraform_test_report.log"        
+          
+          if ! make TESTARGS="2>&1" testacc > "$report_filename"; then
+            echo "EXIT_STATUS=1" >> $GITHUB_ENV
+          fi
+          cat "$report_filename"
         env:
           LINODE_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}
 
-      - name: Convert JSON Report to XML
+      - name: Convert test report to XML
         run: |
-          filename=$(ls | grep -E '^[0-9]{12}_terraform_test_report\.json')
-
+          filename=$(ls | grep -E '^[0-9]{12}_terraform_test_report\.log')
           if [ -f "$filename" ]; then
             go_junit_report_dir=$(go env GOPATH)/bin
             export PATH="$PATH:$go_junit_report_dir"
-            xml_filename=$(echo "$filename" | sed 's/\.json$/.xml/')
-            go-junit-report < "$filename" > "$xml_filename"
-            echo "Conversion from JSON to XML completed successfully."
+            xml_filename=$(echo "$filename" | sed 's/\.log$/.xml/')
+            go-junit-report -in "$filename" -iocopy -out "$xml_filename"
+            echo "Covert to XML completed successfully."
           else
-            echo "JSON test report file not found."
+            echo "Test report file not found."
             exit 1
           fi
         env:
@@ -77,3 +83,12 @@ jobs:
         env:
           LINODE_CLI_OBJ_ACCESS_KEY: ${{ secrets.LINODE_CLI_OBJ_ACCESS_KEY }}
           LINODE_CLI_OBJ_SECRET_KEY: ${{ secrets.LINODE_CLI_OBJ_SECRET_KEY }}
+
+      - name: Test Execution Status Handler
+        run: |
+          if [[ "$EXIT_STATUS" != 0 ]]; then
+            echo "Test execution contains failure(s)"
+            exit $EXIT_STATUS 
+          else
+            echo "Tests passed!"
+          fi
