update names and removing TEST_PKG

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -44,14 +44,14 @@ jobs:
           timestamp=$(date +'%Y%m%d%H%M')
           report_filename="${timestamp}_terraform_test_report.log"        
           
-          if ! make PKG_NAME="linode/firewall" TESTARGS="2>&1" testacc > "$report_filename"; then
+          if ! make TESTARGS="2>&1" testacc > "$report_filename"; then
             echo "EXIT_STATUS=1" >> $GITHUB_ENV
           fi
           cat "$report_filename"
         env:
           LINODE_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}
 
-      - name: Convert JSON Report to XML
+      - name: Convert test report to XML
         run: |
           filename=$(ls | grep -E '^[0-9]{12}_terraform_test_report\.log')
           if [ -f "$filename" ]; then
@@ -59,9 +59,9 @@ jobs:
             export PATH="$PATH:$go_junit_report_dir"
             xml_filename=$(echo "$filename" | sed 's/\.log$/.xml/')
             go-junit-report -in "$filename" -iocopy -out "$xml_filename"
-            echo "Conversion from JSON to XML completed successfully."
+            echo "Covert to XML completed successfully."
           else
-            echo "JSON test report file not found."
+            echo "Test report file not found."
             exit 1
           fi
         env:
